# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - ../XKAudioPlayer/Classes
  
#only_rules: # Only the rules specified in this list will be enabled. Cannot be specified alongside
#  - closure_end_indentation
#  - empty_count
#  - fatal_error_message
#  - first_where
#  - force_unwrapping
#  - implicitly_unwrapped_optional
#  - switch_case_on_newline
#  - overridden_super_call
#  - prohibited_super_call
#  - redundant_nil_coalescing
#  - number_separator
#  - empty_parentheses_with_trailing_closure
#  - legacy_cggeometry_functions
#  - legacy_constant
#  - legacy_constructor
#  - legacy_nsgeometry_functions
#  - mark
#  - redundant_void_return
#  - class_delegate_protocol
#  - compiler_protocol_init
#  - control_statement
#  - custom_rules
#  - cyclomatic_complexity
#  #- file_length
#  - for_where
#  - force_cast
#  - force_try
#  - function_body_length
#  - generic_type_name
#  #- identifier_name
#  - implicit_getter
#  - nesting
#  - redundant_string_enum_value
#  - type_name
#  - unused_enumerated
#  - unused_optional_binding
#  - valid_ibinspectable
#  - weak_delegate
#
#for_where: warning # implicitly
#force_try: warning # implicitly
#force_cast: warning # implicitly
#empty_count: warning # implicitly
#object_literal: warning # implicitly
#
#function_body_length:
#    warning: 50
#
#file_length:
#    warning: 600
#    error: 1200
#
#identifier_name:
#    min_length: 1
#    max_length: 50
#    allowed_symbols: ["_"]
#
#type_name:
#    min_length: 1
#    max_length: 50
