use_frameworks!

platform :ios, '10.0'

target 'XKAudioPlayer_Example' do
  pod 'XKAudioPlayer', :path => '../'

  target 'XKAudioPlayer_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'SwiftLint'
  
end
